repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.3.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.2.2
  hooks:
  - id: yesqa
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.6.4'
  hooks:
  - id: isort
    exclude: "^github|^k8s"
- repo: https://github.com/psf/black
  rev: '20.8b1'
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
    exclude: "^github|^k8s"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.3.0'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: "^github|^k8s"
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  - id: check-symlinks
  - id: debug-statements
# Another entry is required to apply file-contents-sorter to another file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.3.0'
  hooks:
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
- repo: https://github.com/asottile/pyupgrade
  rev: 'v2.7.4'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
    exclude: "^github|^k8s"
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.4'
  hooks:
  - id: flake8
    exclude: "^docs/|^github|^k8s"
