image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG

imagePullSecrets: []

command: []
args: []

port: 9000

resources:
  requests:
    cpu: "0.1"
    memory: 300Mi
  limits:
    cpu: "0.4"
    memory: 600Mi

affinity: {}

tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

logLevel: ERROR

secrets: []

zipkin: {}

sentry: {}
