affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: platform.neuromation.io/job
          operator: Exists

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev-gke-cluster
  sampleRate: 0.01

priorityClassName: ""
