image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG

imagePullSecrets: []

command: []
args: []

port: 9000

resources:
  requests:
    cpu: '0.1'
    memory: 300Mi
  limits:
    cpu: '0.2'
    memory: 600Mi

logLevel: ERROR

secrets: []

zipkin: {}

sentry: {}
